<a href="https://colab.research.google.com/github/Alfi-Lukmanul/Kecerdasan-Buatan/blob/main/Genetic_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math 
from random import randint

In [ ]:
class Genetic_Algorithm:

	populasi_individu = 6 
	individu = ["a", "b", "c", "d"] 
	batasan = {
		'min' : 0,'max' : 10
	} 
	CO_Rate = 0.25 
	M_Rate = 0.1 
	total_generasi = 100
	next_gen = np.arange(4)
	stop = False
	def __init__(self):
		self.chromosome = np.random.randint(self.batasan['min'], self.batasan['max'], size=(self.populasi_individu, len(self.individu)))
		print(self.chromosome)
		print("------------------------------------------------")

		

	def proses(self, chrom, generasi):
		print("Generasi ke ["+str(generasi)+"]")
		
		populasi_individu = len(chrom)
		j = np.arange(populasi_individu)   
		fitness = np.arange(populasi_individu, dtype='f')
		
		for x in range(len(chrom)):
			
			fo = abs((chrom[x][0]+2*chrom[x][1]+3*chrom[x][2]+4*chrom[x][3])-30)
			j[x] = fo
			

			fitn = 1/(fo+1)
      		
			fitness[x] = fitn
			if(fitn == 1):
				self.stop = True
			print("Chromosome {0} : {1}, fitness = {2}".format(x, np.array2string(chrom[x], separator=','), fitn))
		print("Fitness Selesai")
		print(j)
		
		P = np.arange(populasi_individu, dtype='f')
		P = fitness / fitness.sum()
		print("Rata-rata Fungsi Objektif : {}".format(str(np.average(fo))))
		print("Total Fitness : {}".format(str(fitness.sum())))
		print("Probabilitas : {}".format(np.array2string(P, separator=',')))
		print("Probabilitas tertinggi : {}, pada chromosome {}".format(P[P.argmax()], str(P.argmax())))
		print("Chromosome Terpilih Sementara  : {}".format(np.array2string(chrom[P.argmax()], separator=',')),end="\n\n") 

		self.next_gen = chrom[P.argmax()]
		C = np.arange(populasi_individu, dtype='f')
		total_x = 0
		for x in range(len(P)):
			total_x += P[x]
			C[x] = total_x

		R = np.random.sample(len(fitness))
		new_chrom = np.arange(populasi_individu*len(self.individu)).reshape(populasi_individu, len(self.individu))
		
		for y in range(len(R)):
			for k in range(len(new_chrom)):
				if(R[y] < C[0]):
					new_chrom[y] = chrom[0]
				elif((C[k-1] < R[y]) & (R[y] < C[k])):
					new_chrom[y] = chrom[k]
					
		
		R = np.random.sample(populasi_individu)
		index_chrom_parent = [] 
		for p in range(len(R)):
			if(R[p] < self.CO_Rate):
				index_chrom_parent.append(p)

		
		posisi_CO = np.random.randint(low=1, high=len(self.individu), size=len(index_chrom_parent))

		 
		off_spring = np.arange(len(self.individu)*len(index_chrom_parent)).reshape(len(index_chrom_parent), len(self.individu))

		for i_parent in range(len(index_chrom_parent)):
			index_chrome_1 = index_chrom_parent[i_parent]
			if(i_parent == len(index_chrom_parent)-1):
				index_chrome_2 = index_chrom_parent[0]
			else:
				index_chrome_2 = index_chrom_parent[i_parent+1]
			
			cut_point = posisi_CO[i_parent]
			for p in range(len(new_chrom[index_chrome_1])):
				
				if(p >= posisi_CO[i_parent]):
					off_spring[i_parent][p] = new_chrom[index_chrome_2][p]
				else:
					off_spring[i_parent][p] = new_chrom[index_chrome_1][p]

		for x in range(len(off_spring)):
			new_chrom[index_chrom_parent[x]] = off_spring[x]


		
		total_individu = len(chrom) * len(chrom[0])
		jumlah_mutasi = self.M_Rate * total_individu
		jumlah_mutasi = int(jumlah_mutasi)

		random_i_mutasi = np.random.randint(low=0, high=total_individu, size=jumlah_mutasi)

		for x in range(len(random_i_mutasi)):
			index_mutasi = random_i_mutasi[x]
			banyak_kromosom = len(chrom)
			banyak_individu = len(chrom[0]) 
			if(index_mutasi <= banyak_individu):
				new_chrom[0][index_mutasi-1]
			else:
				pos_y = index_mutasi/banyak_individu
				pos_y = int(pos_y)
				pos_x = index_mutasi % banyak_individu
				new_chrom[pos_y][pos_x] = np.random.randint(self.batasan['min'], self.batasan['max'])
		return new_chrom

	def do_now(self):
		chromosome_current = self.chromosome
		for generasi in range(0, self.total_generasi):
			if(self.stop != True):
				chromosome_current = self.proses(chromosome_current, generasi)
		print("---Selesai---")
		print("Chromosome Tertinggi Adalah")
		print(self.next_gen)

run = Genetic_Algorithm()
run.do_now()

[[6 9 0 8]
 [4 9 6 6]
 [4 8 6 6]
 [8 6 5 8]
 [7 2 5 7]
 [7 3 1 5]]
------------------------------------------------
Generasi ke [0]
Chromosome 0 : [6,9,0,8], fitness = 0.037037037037037035
Chromosome 1 : [4,9,6,6], fitness = 0.02857142857142857
Chromosome 2 : [4,8,6,6], fitness = 0.030303030303030304
Chromosome 3 : [8,6,5,8], fitness = 0.02631578947368421
Chromosome 4 : [7,2,5,7], fitness = 0.04
Chromosome 5 : [7,3,1,5], fitness = 0.14285714285714285
Fitness Selesai
[26 34 32 37 24  6]
Rata-rata Fungsi Objektif : 6.0
Total Fitness : 0.3050844
Probabilitas : [0.12139931,0.0936509 ,0.09932671,0.08625741,0.13111125,0.4682545 ]
Probabilitas tertinggi : 0.4682545065879822, pada chromosome 5
Chromosome Terpilih Sementara  : [7,3,1,5]

Generasi ke [1]
Chromosome 0 : [4,9,6,6], fitness = 0.02857142857142857
Chromosome 1 : [7,3,1,5], fitness = 0.14285714285714285
Chromosome 2 : [5,6,5,8], fitness = 0.02857142857142857
Chromosome 3 : [4,8,6,6], fitness = 0.030303030303030304
Chromosome 4 : [4,9,